name: dsckiit_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #  url_launcher: ^5.4.1

  cupertino_icons: ^0.1.2
  flutter_spinkit:
  flutter_launcher_icons:
  firebase_auth: ^0.15.2
  floating_search_bar:
  flutter_statusbarcolor:
  cloud_firestore:
  firebase_storage:
  firebase_core:
  intl:
  cached_network_image:
  image_picker:
  shared_preferences:
  fluttertoast:
  google_sign_in:
  firebase_analytics: 
  

  


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
    image_path: "assets/logo.png"
    android: true
    ios: true



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/dsckiitLogo.png
   - assets/logo.png
   - assets/writting.png
   - assets/welcome.png
   - assets/collab.png
   - assets/events.png
  #  - images/a_dot_ham.jpeg

  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
