name: dsckiit_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #  url_launcher: ^5.4.1

  cupertino_icons: ^0.1.3
  flutter_spinkit: ^4.1.2+1
  flutter_launcher_icons: ^0.7.5
  firebase_auth: ^0.16.0
  floating_search_bar: ^0.3.0
  flutter_statusbarcolor: ^0.2.3
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  firebase_core: ^0.4.4+3
  intl: ^0.16.1
  cached_network_image: ^2.2.0
  image_picker: ^0.6.5+3
  shared_preferences: ^0.5.7
  firebase_database: ^3.1.5
  fluttertoast: ^4.0.1
  google_sign_in: 4.4.4
  firebase_analytics: ^5.0.11
  url_launcher: ^5.4.5
  meet_network_image: ^0.1.2
  line_icons: ^0.2.0
#  pinch_zoom_image: ^0.2.5
  random_string: ^1.1.0
  progress_dialog: ^1.1.0+1
  toast: ^0.1.5
  firebase_messaging: ^5.1.6
  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
    image_path: "assets/logo.png"
    android: true
    ios: true



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/

  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
